version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY_APP: 'fsdf sdfsdf sdf sdfsdfc sdfcsdfcsd'  # Замените на настоящий секретный ключ
      MYSQL_DATABASE: 'policlinic'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123a'

  db:
    image: mysql:latest
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'policlinic'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123a'
      MYSQL_ROOT_PASSWORD: '123ab'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
